name: Publish documentation

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: ./docs
          pre-build-command: "pip install poetry && poetry install"
          build-command: "poetry run sphinx-build -b html . _build"
        
      - name: Set version_name
        id: version_name
        run: echo ::set-output name=version_name::${GITHUB_REF#refs/*/}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          destination_dir: ./docs/en/${{ steps.version_name.outputs.version_name }}
          keep_files: true