name: Run tests

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

jobs:
  code-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check:
          - name: Check code-formatting
            run: poetry run black --check .
          - name: Check import sorting
            run: poetry run isort --check-only

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: ./.github/actions/setup-project

      - name: Check code-formatting
        run: poetry run black --check .
    
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: ./.github/actions/setup-project

      - name: Test with pytest
        run: poetry run pytest --verbose