name: Run tests

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

jobs:
  code-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check:
          - name: Check code-formatting
            run: poetry run black --check .
          - name: Check import sorting
            run: poetry run isort --check-only .
          - name: pylint
            run: poetry run pylint plato

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-py3.9-venv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-py3.9-venv-

      - uses: ./.github/actions/setup-project

      - name: ${{ matrix.check.name }}
        run: ${{ matrix.check.run }}
    
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        include:
          - python-version: 3.9
            coverage: true

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-py${{ matrix.python-version }}-venv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-py${{ matrix.python-version }}-venv-

      - uses: ./.github/actions/setup-project

      - name: Test with pytest
        run: poetry run pytest --verbose
        if: ${{ !matrix.coverage }}
      - name: Test and measure coverage with pytest
        run: poetry run pytest --verbose --cov=plato --cov-report=xml
        if: ${{ matrix.coverage }}
      - uses: codecov/codecov-action@v1